# -*- coding: utf-8 -*-
"""agente2_entrenador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_Y2Vxf5p8sb0BgevyadOX5WYjDhMetE

# Agente 2 — Entrenador
**Dataset:** Telco Customer Churn — recibe el dataset ya limpio del Agente 1

Este agente entrena y compara multiples modelos de clasificacion para predecir churn.
Al finalizar, guarda el mejor modelo y los resultados en `/content/agente2_salida.pkl`
para que el Agente 3 los use en su base de conocimiento RAG.

**Pasos:**
1. Instalacion de dependencias
2. Carga del dataset limpio (salida del Agente 1)
3. Division train / test
4. Entrenamiento con validacion cruzada — Regresion Logistica
5. Entrenamiento con validacion cruzada — Random Forest
6. Entrenamiento con validacion cruzada — Gradient Boosting
7. Entrenamiento con Transformers (DistilBERT + embeddings)
8. Comparativa de modelos y seleccion del mejor
9. Graficos de analisis
10. Exportacion del mejor modelo

## Paso 1 — Instalacion de dependencias
"""

!pip install -q scikit-learn transformers torch pandas numpy matplotlib seaborn

"""## Paso 2 — Carga del dataset limpio"""

import pickle
import pandas as pd
import numpy as np

# Cargar la salida del Agente 1
with open('/content/agente1_salida.pkl', 'rb') as f:
    datos_agente1 = pickle.load(f)

df          = datos_agente1['df_limpio']
encoders    = datos_agente1['encoders']

print(f'Dataset cargado: {df.shape[0]} filas x {df.shape[1]} columnas')
print(f'Columnas: {list(df.columns)}')
print()
print('Distribucion de Churn:')
print(df['Churn'].value_counts())

"""## Paso 3 — Division train / test"""

from sklearn.model_selection import train_test_split

X = df.drop(columns=['Churn'])
y = df['Churn']

# stratify=y garantiza que ambas particiones tengan la misma proporcion de churn
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f'Train: {X_train.shape[0]} muestras')
print(f'Test:  {X_test.shape[0]} muestras')
print()
print(f'Proporcion de churn en train: {y_train.mean():.3f}')
print(f'Proporcion de churn en test:  {y_test.mean():.3f}')

"""## Paso 4 — Regresion Logistica

Modelo lineal simple. Sirve como linea base: si no supera esto,
los modelos mas complejos tienen algun problema.

Se evalua con **validacion cruzada estratificada de 5 folds** para medir
estabilidad (no solo rendimiento en una particion).
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, classification_report
import warnings
warnings.filterwarnings('ignore')

resultados = {}

def entrenar_y_evaluar(nombre, modelo, X_train, y_train, X_test, y_test):
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(modelo, X_train, y_train, cv=cv, scoring='f1')
    modelo.fit(X_train, y_train)
    y_pred = modelo.predict(X_test)
    return {
        'modelo'      : modelo,
        'accuracy'    : round(accuracy_score(y_test, y_pred), 4),
        'f1'          : round(f1_score(y_test, y_pred), 4),
        'cv_f1_media' : round(cv_scores.mean(), 4),
        'cv_f1_std'   : round(cv_scores.std(), 4),
        'y_pred'      : y_pred,
        'reporte'     : classification_report(y_test, y_pred)
    }

lr = LogisticRegression(max_iter=1000, random_state=42)
resultados['Logistic Regression'] = entrenar_y_evaluar(
    'Logistic Regression', lr, X_train, y_train, X_test, y_test
)
r = resultados['Logistic Regression']
print(f'Logistic Regression')
print(f'  Accuracy:    {r["accuracy"]}')
print(f'  F1-Score:    {r["f1"]}')
print(f'  CV F1 media: {r["cv_f1_media"]} +/- {r["cv_f1_std"]}')
print()
print(r['reporte'])

"""## Paso 5 — Random Forest

Ensemble de arboles de decision. Suele manejar bien datos tabulares
con variables mixtas y no requiere escalado previo (aunque ya lo hicimos).
"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
resultados['Random Forest'] = entrenar_y_evaluar(
    'Random Forest', rf, X_train, y_train, X_test, y_test
)
r = resultados['Random Forest']
print(f'Random Forest')
print(f'  Accuracy:    {r["accuracy"]}')
print(f'  F1-Score:    {r["f1"]}')
print(f'  CV F1 media: {r["cv_f1_media"]} +/- {r["cv_f1_std"]}')
print()
print(r['reporte'])

"""## Paso 6 — Gradient Boosting

Entrena arboles de forma secuencial: cada arbol corrige los errores del anterior.
Suele ser el mas preciso en tabular data pero tambien el mas lento.
"""

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(n_estimators=100, random_state=42)
resultados['Gradient Boosting'] = entrenar_y_evaluar(
    'Gradient Boosting', gb, X_train, y_train, X_test, y_test
)
r = resultados['Gradient Boosting']
print(f'Gradient Boosting')
print(f'  Accuracy:    {r["accuracy"]}')
print(f'  F1-Score:    {r["f1"]}')
print(f'  CV F1 media: {r["cv_f1_media"]} +/- {r["cv_f1_std"]}')
print()
print(r['reporte'])

"""## Paso 7 — Transformers (DistilBERT + embeddings)

En lugar de usar DistilBERT como clasificador directo, lo usamos como **extractor de features**:
1. Cada fila del dataset se convierte a una descripcion textual breve
2. DistilBERT produce un vector de 768 dimensiones para cada texto (vector `[CLS]`)
3. Una regresion logistica simple entrena sobre esos vectores

Se trabaja sobre una muestra para que corra en CPU en tiempo razonable.
"""

from transformers import AutoTokenizer, AutoModel
from sklearn.linear_model import LogisticRegression as LR_emb
import torch

MODELO_BERT  = 'distilbert-base-uncased'
MUESTRA_BERT = 600

print('Cargando DistilBERT...')
tokenizador  = AutoTokenizer.from_pretrained(MODELO_BERT)
modelo_bert  = AutoModel.from_pretrained(MODELO_BERT)
print('Modelo cargado.')

def fila_a_texto(fila, columnas):
    """Convierte una fila numerica a una descripcion textual usando los nombres de columna."""
    partes = []
    for col in columnas[:8]:
        partes.append(f'{col} {round(float(fila[col]), 2)}')
    return ' '.join(partes)

def obtener_embeddings(textos, tokenizador, modelo):
    """Extrae el vector [CLS] de cada texto. Es el vector que resume toda la secuencia."""
    embeddings = []
    modelo.eval()
    with torch.no_grad():
        for texto in textos:
            tokens = tokenizador(
                texto,
                return_tensors='pt',
                truncation=True,
                max_length=64,
                padding='max_length'
            )
            salida = modelo(**tokens)
            # last_hidden_state[:, 0, :] es el vector del token [CLS] (posicion 0)
            vector_cls = salida.last_hidden_state[:, 0, :].squeeze().numpy()
            embeddings.append(vector_cls)
    return np.array(embeddings)

columnas = list(X_train.columns)

# Muestra de train
idx_train   = X_train.index[:MUESTRA_BERT]
textos_train = [fila_a_texto(X_train.loc[i], columnas) for i in idx_train]
y_train_mst  = y_train.loc[idx_train]

# Muestra de test
idx_test    = X_test.index[:int(MUESTRA_BERT * 0.25)]
textos_test  = [fila_a_texto(X_test.loc[i], columnas) for i in idx_test]
y_test_mst   = y_test.loc[idx_test]

print(f'Extrayendo embeddings: {len(textos_train)} train / {len(textos_test)} test...')
X_emb_train = obtener_embeddings(textos_train, tokenizador, modelo_bert)
X_emb_test  = obtener_embeddings(textos_test,  tokenizador, modelo_bert)
print(f'Shape embeddings: {X_emb_train.shape}  (cada fila = vector de 768 dims)')

# Entrenar clasificador sobre los embeddings de DistilBERT
clf_emb = LR_emb(max_iter=500, random_state=42)
clf_emb.fit(X_emb_train, y_train_mst)
y_pred_emb = clf_emb.predict(X_emb_test)

resultados['Transformers + LR (embeddings)'] = {
    'modelo'      : clf_emb,
    'accuracy'    : round(accuracy_score(y_test_mst, y_pred_emb), 4),
    'f1'          : round(f1_score(y_test_mst, y_pred_emb, zero_division=0), 4),
    'cv_f1_media' : 'N/A',
    'cv_f1_std'   : 'N/A',
    'y_pred'      : y_pred_emb,
    'reporte'     : classification_report(y_test_mst, y_pred_emb)
}
r = resultados['Transformers + LR (embeddings)']
print(f'Transformers + LR (embeddings)')
print(f'  Accuracy: {r["accuracy"]}')
print(f'  F1-Score: {r["f1"]}  (sobre muestra de {len(y_test_mst)} test)')
print()
print(r['reporte'])

"""## Paso 8 — Comparativa y seleccion del mejor modelo"""

# Tabla comparativa
print(f'{"Modelo":<38} {"Accuracy":>9} {"F1":>7} {"CV F1":>8} {"Std":>7}')
print('-' * 72)
for nombre, d in resultados.items():
    print(f'{nombre:<38} {str(d["accuracy"]):>9} {str(d["f1"]):>7} '
          f'{str(d["cv_f1_media"]):>8} {str(d["cv_f1_std"]):>7}')

# Seleccionar el modelo con mayor F1-Score
mejor_nombre = max(
    resultados,
    key=lambda n: resultados[n]['f1'] if isinstance(resultados[n]['f1'], float) else 0.0
)
mejor_modelo = resultados[mejor_nombre]['modelo']

print(f'Mejor modelo: {mejor_nombre}')
print(f'  F1-Score:  {resultados[mejor_nombre]["f1"]}')
print(f'  Accuracy:  {resultados[mejor_nombre]["accuracy"]}')
print()
print('Se usa F1-Score como criterio de seleccion porque el dataset tiene')
print('desbalance de clases: el accuracy puede ser alto simplemente prediciendo')
print('siempre "No churn", pero eso no sirve para detectar clientes que van a irse.')

"""## Paso 9 — Graficos de analisis"""

import matplotlib.pyplot as plt
import seaborn as sns

# Grafico 1: comparativa de F1-Score por modelo
nombres  = list(resultados.keys())
f1s      = [d['f1'] if isinstance(d['f1'], float) else 0.0 for d in resultados.values()]
colores  = ['#e05c5c' if n == mejor_nombre else '#5c7cde' for n in nombres]

fig, ax = plt.subplots(figsize=(10, 5))
barras = ax.barh(nombres, f1s, color=colores, edgecolor='white')
ax.set_xlabel('F1-Score')
ax.set_xlim(0, 1)
ax.set_title('Agente 2 — Comparativa de F1-Score por modelo')
for barra, valor in zip(barras, f1s):
    ax.text(valor + 0.01, barra.get_y() + barra.get_height() / 2,
            f'{valor:.4f}', va='center', fontsize=10)
plt.tight_layout()
plt.savefig('/content/agente2_f1_comparativa.png', dpi=150)
plt.show()

# Grafico 2: accuracy vs F1 por modelo (solo modelos sklearn con ambas metricas)
nombres_sk  = [n for n in resultados if resultados[n]['cv_f1_media'] != 'N/A']
accs        = [resultados[n]['accuracy'] for n in nombres_sk]
f1s_sk      = [resultados[n]['f1']       for n in nombres_sk]
cv_medias   = [resultados[n]['cv_f1_media'] for n in nombres_sk]
cv_stds     = [resultados[n]['cv_f1_std']   for n in nombres_sk]

x = range(len(nombres_sk))
fig, ax = plt.subplots(figsize=(10, 5))
ax.bar([i - 0.2 for i in x], accs,     0.35, label='Accuracy',     color='#5c7cde', alpha=0.85)
ax.bar([i + 0.2 for i in x], f1s_sk,   0.35, label='F1-Score test', color='#e05c5c', alpha=0.85)
ax.errorbar(
    [i + 0.2 for i in x], cv_medias,
    yerr=cv_stds, fmt='o', color='#2c2c2a',
    capsize=5, label='CV F1 media +/- std'
)
ax.set_xticks(list(x))
ax.set_xticklabels(nombres_sk, rotation=10)
ax.set_ylim(0, 1)
ax.set_ylabel('Score')
ax.set_title('Agente 2 — Accuracy vs F1 con varianza de CV')
ax.legend()
plt.tight_layout()
plt.savefig('/content/agente2_accuracy_vs_f1.png', dpi=150)
plt.show()

# Grafico 3: matriz de confusion del mejor modelo
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

clases = encoders['Churn'].classes_

# Obtener predicciones del mejor modelo sobre el test set completo
if mejor_nombre != 'Transformers + LR (embeddings)':
    y_pred_mejor = resultados[mejor_nombre]['y_pred']
    cm = confusion_matrix(y_test, y_pred_mejor)
else:
    # Para el modelo de embeddings usamos la muestra de test
    cm = confusion_matrix(y_test_mst, resultados[mejor_nombre]['y_pred'])

fig, ax = plt.subplots(figsize=(6, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=clases)
disp.plot(ax=ax, colorbar=False, cmap='Blues')
ax.set_title(f'Agente 2 — Matriz de confusion\n{mejor_nombre}')
plt.tight_layout()
plt.savefig('/content/agente2_confusion.png', dpi=150)
plt.show()

# Grafico 4: importancia de variables (solo para Random Forest y Gradient Boosting)
modelos_con_importancia = {
    n: d for n, d in resultados.items()
    if hasattr(d['modelo'], 'feature_importances_')
}

if modelos_con_importancia:
    fig, axes = plt.subplots(1, len(modelos_con_importancia), figsize=(14, 6))
    if len(modelos_con_importancia) == 1:
        axes = [axes]

    for ax, (nombre, datos) in zip(axes, modelos_con_importancia.items()):
        importancias = datos['modelo'].feature_importances_
        indices = np.argsort(importancias)[-12:]  # top 12
        ax.barh(
            X_train.columns[indices],
            importancias[indices],
            color='#5c7cde', edgecolor='white'
        )
        ax.set_title(f'{nombre}\nTop 12 variables')
        ax.set_xlabel('Importancia')

    fig.suptitle('Agente 2 — Importancia de variables por modelo', fontsize=12)
    plt.tight_layout()
    plt.savefig('/content/agente2_importancia.png', dpi=150)
    plt.show()

"""## Paso 10 — Exportacion del mejor modelo y resultados"""

# Guardar todo lo necesario para el Agente 3
salida_agente2 = {
    'mejor_modelo'  : mejor_modelo,
    'mejor_nombre'  : mejor_nombre,
    'resultados'    : resultados,
    'X_train'       : X_train,
    'X_test'        : X_test,
    'y_train'       : y_train,
    'y_test'        : y_test,
    'X'             : X,
    'y'             : y,
}

with open('/content/agente2_salida.pkl', 'wb') as f:
    pickle.dump(salida_agente2, f)

print('Archivo guardado en /content/agente2_salida.pkl')
print()
print(f'Mejor modelo exportado: {mejor_nombre}')
print(f'  F1-Score: {resultados[mejor_nombre]["f1"]}')
print(f'  Accuracy: {resultados[mejor_nombre]["accuracy"]}')