# -*- coding: utf-8 -*-
"""agente3_comunicador_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3Y1PRkr7QaZaEry-CjUAJ586t53Iw7q

# Agente 3 — Comunicador RAG
**Recibe:** resultados del Agente 1 y Agente 2 via archivos `.pkl`

Este agente responde preguntas en lenguaje natural sobre el analisis realizado.
Usa el patron **RAG (Retrieval Augmented Generation)**:
en lugar de generar respuestas libremente, primero recupera fragmentos relevantes
de una base de conocimiento y los usa como contexto para responder.

**Pasos:**
1. Instalacion de dependencias
2. Carga de resultados del Agente 1 y Agente 2
3. Construccion de la base de conocimiento (documentos de texto)
4. Generacion de embeddings con SentenceTransformer
5. Indexacion vectorial con FAISS
6. Funcion de busqueda semantica
7. Carga del modelo generador (flan-t5-base)
8. Pipeline RAG completo
9. Sesion de preguntas y respuestas
10. Graficos del sistema RAG

## Paso 1 — Instalacion de dependencias
"""

# sentence-transformers: genera embeddings de texto (para indexar y buscar)
# faiss-cpu: base vectorial para busqueda por similitud
# transformers: modelo generador de texto (flan-t5-base)
!pip install -q sentence-transformers faiss-cpu transformers torch pandas numpy matplotlib

"""## Paso 2 — Carga de resultados de los agentes anteriores"""

import pickle
import numpy as np
import pandas as pd

# Cargar salidas de ambos agentes
with open('/content/agente1_salida.pkl', 'rb') as f:
    datos_a1 = pickle.load(f)

with open('/content/agente2_salida.pkl', 'rb') as f:
    datos_a2 = pickle.load(f)

# Extraer lo que necesitamos
encoders      = datos_a1['encoders']
cols_numericas   = datos_a1['cols_numericas']
cols_categoricas = datos_a1['cols_categoricas']

mejor_nombre  = datos_a2['mejor_nombre']
mejor_modelo  = datos_a2['mejor_modelo']
resultados    = datos_a2['resultados']
X_train       = datos_a2['X_train']
X_test        = datos_a2['X_test']
y_train       = datos_a2['y_train']
y_test        = datos_a2['y_test']
X             = datos_a2['X']
y             = datos_a2['y']

print('Datos cargados correctamente.')
print(f'  Mejor modelo del Agente 2: {mejor_nombre}')
print(f'  F1-Score: {resultados[mejor_nombre]["f1"]}')
print(f'  Modelos disponibles: {list(resultados.keys())}')

"""## Paso 3 — Construccion de la base de conocimiento

La base de conocimiento es una lista de fragmentos de texto que describen
distintos aspectos del analisis: el dataset, el preprocesamiento, cada modelo
y sus metricas, y la conclusion final.

Cada fragmento cubre un tema distinto para que FAISS pueda recuperar
el mas relevante segun la pregunta del usuario.
"""

documentos = []

# Fragmento 1: descripcion general del dataset
documentos.append(
    f'El dataset de Telco Customer Churn contiene {X.shape[0]} clientes '
    f'y {X.shape[1]} variables predictoras. La variable objetivo es Churn, '
    f'que indica si el cliente cancelo el servicio de telecomunicaciones. '
    f'Se uso un 80 por ciento para entrenamiento ({X_train.shape[0]} muestras) '
    f'y un 20 por ciento para prueba ({X_test.shape[0]} muestras). '
    f'El dataset presenta desbalance de clases: hay mas clientes que no cancelaron '
    f'que clientes que si cancelaron.'
)

# Fragmento 2: preprocesamiento del Agente 1
documentos.append(
    f'El Agente 1 Normalizador realizo el siguiente preprocesamiento sobre el dataset crudo: '
    f'elimino la columna customerID por ser un identificador sin valor predictivo, '
    f'convirtio TotalCharges de texto a numero porque venia con espacios vacios en lugar de NaN, '
    f'imputo los valores faltantes usando la mediana en las {len(cols_numericas)} columnas numericas '
    f'y la moda en las {len(cols_categoricas)} columnas categoricas, '
    f'escalo las columnas numericas con StandardScaler para media 0 y desviacion estandar 1, '
    f'y codifico las columnas categoricas con LabelEncoder.'
)

# Fragmento 3: descripcion de los modelos entrenados por el Agente 2
nombres_modelos = list(resultados.keys())
documentos.append(
    f'El Agente 2 Entrenador entreno {len(nombres_modelos)} modelos de clasificacion: '
    + ', '.join(nombres_modelos) + '. '
    f'Los tres modelos sklearn se evaluaron con validacion cruzada estratificada de 5 folds '
    f'para medir su estabilidad. El modelo Transformers uso DistilBERT para extraer embeddings '
    f'de filas del dataset representadas como texto y entreno una regresion logistica sobre esos vectores.'
)

# Fragmento por cada modelo con sus metricas
for nombre, datos in resultados.items():
    documentos.append(
        f'El modelo {nombre} obtuvo los siguientes resultados: '
        f'accuracy igual a {datos["accuracy"]}, '
        f'F1-Score igual a {datos["f1"]}, '
        f'CV F1 media igual a {datos["cv_f1_media"]}, '
        f'desviacion estandar del CV igual a {datos["cv_f1_std"]}.'
    )

# Fragmento de conclusion
mejor = resultados[mejor_nombre]
documentos.append(
    f'El modelo seleccionado como el mejor fue {mejor_nombre} '
    f'con un F1-Score de {mejor["f1"]} y accuracy de {mejor["accuracy"]}. '
    f'La seleccion se hizo por F1-Score y no por accuracy porque el dataset '
    f'tiene desbalance de clases. Un modelo que predice siempre que el cliente '
    f'no cancela tendria alto accuracy pero no detectaria los churns reales.'
)

print(f'Base de conocimiento construida: {len(documentos)} fragmentos')
for i, doc in enumerate(documentos):
    print(f'\n[{i}] {doc[:120]}...')

"""## Paso 4 — Generacion de embeddings con SentenceTransformer

`all-MiniLM-L6-v2` convierte cada fragmento de texto a un vector de 384 dimensiones.
Vectores de textos con significado similar quedan cercanos en ese espacio.
"""

from sentence_transformers import SentenceTransformer

print('Cargando modelo de embeddings (all-MiniLM-L6-v2)...')
modelo_emb = SentenceTransformer('all-MiniLM-L6-v2')

# normalize_embeddings=True es necesario para usar IndexFlatIP como similitud coseno
vectores_docs = modelo_emb.encode(documentos, normalize_embeddings=True)

print(f'Embeddings generados.')
print(f'  Documentos: {vectores_docs.shape[0]}')
print(f'  Dimension de cada vector: {vectores_docs.shape[1]}')

"""## Paso 5 — Indexacion vectorial con FAISS

FAISS (Facebook AI Similarity Search) es una libreria de busqueda por similitud.
Usamos `IndexFlatIP` (producto interno) que con vectores normalizados
es equivalente a similitud coseno: devuelve los documentos mas parecidos
semanticamente a la pregunta.
"""

import faiss

dimension     = vectores_docs.shape[1]
indice_faiss  = faiss.IndexFlatIP(dimension)
indice_faiss.add(np.array(vectores_docs, dtype='float32'))

print(f'Indice FAISS creado.')
print(f'  Vectores indexados: {indice_faiss.ntotal}')
print(f'  Dimension: {dimension}')

"""## Paso 6 — Funcion de busqueda semantica

Dado una pregunta en texto, esta funcion:
1. La convierte a vector con el mismo modelo de embeddings
2. Busca en FAISS los `top_k` documentos mas similares
3. Devuelve esos fragmentos como contexto
"""

TOP_K = 3   # cuantos fragmentos recuperar por pregunta

def buscar_contexto(pregunta, top_k=TOP_K):
    """
    Convierte la pregunta a embedding y recupera los fragmentos
    mas relevantes de la base de conocimiento usando FAISS.
    """
    vector_pregunta = modelo_emb.encode([pregunta], normalize_embeddings=True)
    scores, indices = indice_faiss.search(
        np.array(vector_pregunta, dtype='float32'), top_k
    )
    fragmentos = [documentos[i] for i in indices[0]]
    return fragmentos, scores[0]

# Prueba de busqueda
pregunta_prueba = 'Cual fue el mejor modelo?'
fragmentos, scores = buscar_contexto(pregunta_prueba)
print(f'Pregunta: {pregunta_prueba}')
print(f'Fragmentos recuperados (similitud coseno):')
for i, (frag, score) in enumerate(zip(fragmentos, scores)):
    print(f'  [{i}] score={score:.4f} -> {frag[:100]}...')

"""## Paso 7 — Carga del modelo generador

`flan-t5-base` es un modelo sequence-to-sequence de Google.
Toma como entrada un prompt con contexto + pregunta y genera una respuesta de texto.
"""

from transformers import pipeline as hf_pipeline

print('Cargando flan-t5-base...')
generador = hf_pipeline(
    'text-generation',
    model='gpt2',
    max_new_tokens=180
)
print('Modelo generador listo.')

"""## Paso 8 — Pipeline RAG completo

Este es el flujo completo que ejecuta el Agente 3 para cada pregunta:

```
pregunta
   |
   v
embedding (SentenceTransformer)
   |
   v
busqueda FAISS -> top 3 fragmentos
   |
   v
prompt = contexto + pregunta
   |
   v
flan-t5-base -> respuesta en texto
```
"""

def responder(pregunta):
    """
    Pipeline RAG completo:
    1. Convierte la pregunta a embedding
    2. Recupera los fragmentos mas relevantes de FAISS
    3. Arma el prompt con contexto + pregunta
    4. Genera la respuesta con GPT2
    """
    # Paso 1 y 2: busqueda semantica
    fragmentos, scores = buscar_contexto(pregunta)
    contexto = ' '.join(fragmentos)

    # Paso 3: construir el prompt
    prompt = (
        'Based on the following information about a machine learning analysis, '
        'answer the question in Spanish.\n\n'
        f'Context: {contexto}\n\n'
        f'Question: {pregunta}\n\n'
        'Answer:'
    )

    # Paso 4: generar respuesta
    salida = generador(prompt)
    texto_completo = salida[0]['generated_text']
    if 'Answer:' in texto_completo:
        respuesta = texto_completo.split('Answer:')[-1].strip()
    else:
        respuesta = texto_completo[len(prompt):].strip()

    return respuesta, fragmentos, scores

# Prueba del pipeline completo
resp, frags, scs = responder('Cual fue el mejor modelo y que F1-Score obtuvo?')
print(f'Respuesta: {resp}')

"""## Paso 9 — Sesion de preguntas y respuestas"""

preguntas = [
    'Cual fue el mejor modelo y que F1-Score obtuvo?',
    'Cuantos clientes tiene el dataset?',
    'Que transformaciones aplico el Agente 1 sobre los datos?',
    'Que modelos se entrenaron y como se comparan?',
    'Por que se usa F1-Score en lugar de accuracy?',
    'Como funciona el modelo de Transformers en el Agente 2?',
]

for pregunta in preguntas:
    resp, _, _ = responder(pregunta)
    print(f'Pregunta: {pregunta}')
    print(f'Respuesta: {resp}')
    print('-' * 60)

# Sesion interactiva
pregunta_libre = input('Escribi tu pregunta: ')
resp, fragmentos_usados, scores_usados = responder(pregunta_libre)
print(f'\nRespuesta: {resp}')
print(f'\nFragmentos recuperados por FAISS:')
for i, (frag, score) in enumerate(zip(fragmentos_usados, scores_usados)):
    print(f'  [{i}] similitud={score:.4f} -> {frag[:120]}...')

"""## Paso 10 — Graficos del sistema RAG"""

import matplotlib.pyplot as plt
import numpy as np

# Grafico 1: scores de similitud para cada pregunta de ejemplo
fig, ax = plt.subplots(figsize=(12, 6))

preguntas_cortas = [p[:40] + '...' for p in preguntas]
todos_scores = []
for p in preguntas:
    _, frags, scs = responder(p)
    todos_scores.append(scs)

x     = np.arange(len(preguntas_cortas))
width = 0.25
colores_barras = ['#5c7cde', '#e05c5c', '#5cb85c']

for i in range(TOP_K):
    scores_i = [s[i] for s in todos_scores]
    ax.bar(x + i * width, scores_i, width, label=f'Fragmento {i+1}',
           color=colores_barras[i], alpha=0.85, edgecolor='white')

ax.set_xticks(x + width)
ax.set_xticklabels(preguntas_cortas, rotation=20, ha='right', fontsize=9)
ax.set_ylabel('Similitud coseno')
ax.set_ylim(0, 1)
ax.set_title('Agente 3 — Similitud FAISS por pregunta (top 3 fragmentos)')
ax.legend()
plt.tight_layout()
plt.savefig('/content/agente3_similitud_faiss.png', dpi=150)
plt.show()

# Grafico 2: mapa de calor — que fragmentos recupera FAISS para cada pregunta
fig, ax = plt.subplots(figsize=(12, 6))

matriz_indices = []
for p in preguntas:
    vector_p = modelo_emb.encode([p], normalize_embeddings=True)
    scs_all, idx_all = indice_faiss.search(
        np.array(vector_p, dtype='float32'), len(documentos)
    )
    # Score para cada fragmento (en orden de documento, no de ranking)
    scores_ordenados = [0.0] * len(documentos)
    for idx, score in zip(idx_all[0], scs_all[0]):
        scores_ordenados[idx] = float(score)
    matriz_indices.append(scores_ordenados)

import seaborn as sns
etiquetas_docs = [f'Doc {i}' for i in range(len(documentos))]
etiquetas_pregs = [p[:35] + '...' for p in preguntas]

ax.set_title('Agente 3 — Mapa de recuperacion FAISS\n(similitud coseno pregunta x fragmento)')
sns.heatmap(
    np.array(matriz_indices),
    xticklabels=etiquetas_docs,
    yticklabels=etiquetas_pregs,
    annot=True, fmt='.2f',
    cmap='YlOrRd', ax=ax,
    linewidths=0.3
)
plt.tight_layout()
plt.savefig('/content/agente3_heatmap_rag.png', dpi=150)
plt.show()

# Grafico 3: visualizacion 2D de los embeddings (PCA)
from sklearn.decomposition import PCA

# Embeddings de los documentos + preguntas de ejemplo
textos_todos  = documentos + preguntas
vectores_todos = modelo_emb.encode(textos_todos, normalize_embeddings=True)

pca   = PCA(n_components=2)
coords = pca.fit_transform(vectores_todos)

fig, ax = plt.subplots(figsize=(10, 7))

n_docs  = len(documentos)
n_pregs = len(preguntas)

# Documentos de la base de conocimiento
ax.scatter(coords[:n_docs, 0], coords[:n_docs, 1],
           c='#5c7cde', s=120, zorder=3, label='Documentos (base RAG)')
for i, doc in enumerate(documentos):
    ax.annotate(f'Doc {i}', (coords[i, 0], coords[i, 1]),
                fontsize=8, xytext=(4, 4), textcoords='offset points')

# Preguntas de ejemplo
ax.scatter(coords[n_docs:, 0], coords[n_docs:, 1],
           c='#e05c5c', s=80, marker='^', zorder=3, label='Preguntas')
for i, p in enumerate(preguntas):
    ax.annotate(f'P{i+1}', (coords[n_docs+i, 0], coords[n_docs+i, 1]),
                fontsize=8, xytext=(4, 4), textcoords='offset points', color='#a00000')

ax.set_title('Agente 3 — Espacio de embeddings (PCA 2D)\nDocumentos vs Preguntas')
ax.set_xlabel('Componente 1')
ax.set_ylabel('Componente 2')
ax.legend()
plt.tight_layout()
plt.savefig('/content/agente3_embeddings_pca.png', dpi=150)
plt.show()