# -*- coding: utf-8 -*-
"""agente1_normalizador.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJ7OwKklrSAvbaRhEC1H8OO0evPzOt7R

# Agente 1 — Normalizador
**Dataset:** Telco Customer Churn (IBM / Kaggle)

Este agente recibe el CSV crudo y produce un dataset limpio listo para entrenar.
Al finalizar, guarda el resultado en `/content/df_limpio.pkl` para que el Agente 2 lo levante.

**Pasos:**
1. Instalacion de dependencias
2. Configuracion de Kaggle y descarga del dataset
3. Inspeccion del dataset crudo
4. Limpieza de tipos y columnas
5. Imputacion de valores faltantes
6. Escalado de variables numericas
7. Codificacion de variables categoricas
8. Graficos de analisis exploratorio
9. Exportacion del dataset limpio

## Paso 1 — Instalacion de dependencias
"""

# Solo necesitamos las librerias de preprocesamiento en este agente
!pip install -q kaggle scikit-learn pandas numpy matplotlib seaborn

"""## Paso 2 — Configuracion de Kaggle y descarga del dataset"""

from google.colab import files
import os

# Subir el archivo kaggle.json (descargarlo desde kaggle.com/settings -> API -> Create New Token)
uploaded = files.upload()

os.makedirs('/root/.kaggle', exist_ok=True)
os.rename('kaggle.json', '/root/.kaggle/kaggle.json')
os.chmod('/root/.kaggle/kaggle.json', 0o600)

print('Credenciales configuradas correctamente.')

import pandas as pd
import numpy as np

# Descarga directa via API — sin necesidad de bajar el archivo a mano
!kaggle datasets download -d blastchar/telco-customer-churn --unzip -p /content/data

df_raw = pd.read_csv('/content/data/WA_Fn-UseC_-Telco-Customer-Churn.csv')

print(f'Dataset cargado: {df_raw.shape[0]} filas x {df_raw.shape[1]} columnas')
df_raw.head(4)

"""## Paso 3 — Inspeccion del dataset crudo"""

# Ver tipos de cada columna antes de cualquier transformacion
print('=== Tipos de columnas ===')
print(df_raw.dtypes)
print()

# Valores nulos reales
print('=== Valores nulos (NaN) ===')
nulos = df_raw.isnull().sum()
print(nulos[nulos > 0] if nulos.sum() > 0 else 'Sin valores nulos detectados por pandas.')
print()

# TotalCharges viene como string — pandas no lo detecta como nulo
# pero tiene espacios vacios que hay que tratar manualmente
print('=== Problema en TotalCharges ===')
filas_vacias = df_raw[df_raw['TotalCharges'].str.strip() == '']
print(f'{len(filas_vacias)} filas con TotalCharges vacio (espacio en blanco, no NaN)')
print(filas_vacias[['customerID', 'tenure', 'TotalCharges', 'Churn']].head())

# Distribucion de la variable objetivo antes de cualquier cambio
print('=== Distribucion de Churn (variable objetivo) ===')
conteo = df_raw['Churn'].value_counts()
print(conteo)
print(f'\nPorcentaje de churn: {conteo["Yes"] / len(df_raw) * 100:.1f}%')
print('Hay desbalance de clases — mas clientes que NO cancelaron que los que SI cancelaron.')

"""## Paso 4 — Limpieza de tipos y eliminacion de columnas irrelevantes

`customerID` es un identificador unico por fila. No tiene valor predictivo:
si el modelo lo aprende, simplemente memoriza filas en lugar de generalizar.

`TotalCharges` viene como `object` con espacios vacios. Hay que convertirla a `float`
antes de poder imputar o escalar.
"""

df = df_raw.copy()

# customerID no aporta informacion predictiva — la eliminamos
df.drop(columns=['customerID'], inplace=True)
print('customerID eliminada.')

# Convertir TotalCharges: reemplazar espacios vacios por NaN y castear a float
df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Verificar que ahora si aparece como float con NaN donde corresponde
print(f'TotalCharges dtype ahora: {df["TotalCharges"].dtype}')
print(f'NaN en TotalCharges: {df["TotalCharges"].isna().sum()}')
print()
print(df.dtypes)

"""## Paso 5 — Imputacion de valores faltantes

Estrategia:
- Columnas **numericas**: imputar con la **mediana** (robusta ante outliers)
- Columnas **categoricas**: imputar con la **moda** (valor mas frecuente)
"""

from sklearn.impute import SimpleImputer

# Identificar columnas por tipo (excluyendo la variable objetivo por ahora)
cols_numericas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
cols_categoricas = [
    c for c in df.select_dtypes(include='object').columns
    if c != 'Churn'
]

print(f'Columnas numericas ({len(cols_numericas)}): {cols_numericas}')
print(f'Columnas categoricas ({len(cols_categoricas)}): {cols_categoricas}')

# Imputar numericas con mediana
imputer_num = SimpleImputer(strategy='median')
df[cols_numericas] = imputer_num.fit_transform(df[cols_numericas])

# Imputar categoricas con moda
imputer_cat = SimpleImputer(strategy='most_frequent')
df[cols_categoricas] = imputer_cat.fit_transform(df[cols_categoricas])

# Verificar que no queden nulos
print(f'Nulos restantes: {df.isnull().sum().sum()}')
print('Imputacion completada.')

"""## Paso 6 — Escalado de variables numericas

`StandardScaler` transforma cada variable numerica para que tenga
**media 0 y desviacion estandar 1**. Esto es necesario para modelos
sensibles a la magnitud de las variables (como regresion logistica).
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[cols_numericas] = scaler.fit_transform(df[cols_numericas])

print('Escalado completado. Estadisticas post-escalado:')
print(df[cols_numericas].describe().round(3))

"""## Paso 7 — Codificacion de variables categoricas

`LabelEncoder` convierte cada categoria de texto a un numero entero.
Por ejemplo: `Female -> 0`, `Male -> 1`.

Guardamos cada encoder por columna para poder invertir la transformacion si hace falta.
"""

from sklearn.preprocessing import LabelEncoder

encoders = {}

# Codificar columnas categoricas (sin la objetivo)
for col in cols_categoricas:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    encoders[col] = le

# Codificar la variable objetivo por separado
le_churn = LabelEncoder()
df['Churn'] = le_churn.fit_transform(df['Churn'].astype(str))
encoders['Churn'] = le_churn

print('Codificacion completada.')
print(f'Clases de Churn: {le_churn.classes_} -> {le_churn.transform(le_churn.classes_)}')
print()
print('Primeras 3 filas del dataset procesado:')
print(df.head(3).to_string())

"""## Paso 8 — Graficos de analisis exploratorio"""

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle('Agente 1 — Analisis del dataset Telco Churn', fontsize=13)

# Grafico 1: distribucion de la variable objetivo
conteo_churn = df_raw['Churn'].value_counts()
colores_churn = ['#5c7cde', '#e05c5c']
axes[0].pie(
    conteo_churn,
    labels=['No churn', 'Churn'],
    autopct='%1.1f%%',
    colors=colores_churn,
    startangle=90
)
axes[0].set_title('Distribucion de Churn')

# Grafico 2: valores faltantes antes y despues de la imputacion
categorias = ['Antes (TotalCharges vacias)', 'Despues (imputadas)']
valores = [len(df_raw[df_raw['TotalCharges'].str.strip() == '']), 0]
axes[1].bar(categorias, valores, color=['#e05c5c', '#5cb85c'], width=0.4)
axes[1].set_ylabel('Filas con valores faltantes')
axes[1].set_title('Efecto de la imputacion')
for i, v in enumerate(valores):
    axes[1].text(i, v + 0.1, str(v), ha='center', fontsize=12)

plt.tight_layout()
plt.savefig('/content/agente1_distribucion.png', dpi=150)
plt.show()

# Grafico: distribucion de las variables numericas antes vs despues del escalado
fig, axes = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle('Agente 1 — Distribucion de variables numericas (post-escalado)', fontsize=12)

for ax, col in zip(axes, cols_numericas):
    ax.hist(df[col], bins=30, color='#5c7cde', edgecolor='white', alpha=0.85)
    ax.set_title(col)
    ax.set_xlabel('Valor escalado')
    ax.set_ylabel('Frecuencia')

plt.tight_layout()
plt.savefig('/content/agente1_numericas.png', dpi=150)
plt.show()

# Grafico: matriz de correlacion del dataset limpio
fig, ax = plt.subplots(figsize=(14, 10))
correlacion = df.corr()
mascara = correlacion.abs() < 0.1   # ocultar correlaciones muy bajas para legibilidad
sns.heatmap(
    correlacion,
    mask=mascara,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    center=0,
    linewidths=0.4,
    ax=ax
)
ax.set_title('Agente 1 — Correlacion entre variables (valores absolutos > 0.1)', fontsize=12)
plt.tight_layout()
plt.savefig('/content/agente1_correlacion.png', dpi=150)
plt.show()

"""## Paso 9 — Exportacion del dataset limpio"""

import pickle

# Guardamos el dataset limpio y los objetos de transformacion
# para que el Agente 2 pueda cargarlos directamente
salida = {
    'df_limpio': df,
    'cols_numericas': cols_numericas,
    'cols_categoricas': cols_categoricas,
    'scaler': scaler,
    'encoders': encoders,
    'imputer_num': imputer_num,
    'imputer_cat': imputer_cat,
}

with open('/content/agente1_salida.pkl', 'wb') as f:
    pickle.dump(salida, f)

print('Archivo guardado en /content/agente1_salida.pkl')
print(f'Dataset limpio: {df.shape[0]} filas x {df.shape[1]} columnas')
print()
print('Resumen del preprocesamiento:')
print(f'  - customerID eliminada')
print(f'  - TotalCharges convertida de string a float')
print(f'  - {df.isnull().sum().sum()} valores nulos restantes')
print(f'  - {len(cols_numericas)} columnas numericas escaladas con StandardScaler')
print(f'  - {len(cols_categoricas)} columnas categoricas codificadas con LabelEncoder')
print(f'  - Variable objetivo Churn: 0 = No cancelo, 1 = Cancelo')
