# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2I8z0dSBVi96tCjXXy8ewzm0Che1meQ

# 🗂️ Paso A — Exploración del dataset crudo
Objetivo: entender la estructura del CSV antes de normalizar.

# Celda 1 — Instalación
"""

from google.colab import drive
drive.mount('/content/drive')

# No necesitamos nada especial, pandas ya viene en Colab
import pandas as pd
import numpy as np

print("✅ Librerías listas")

"""#Celda 2 — Cargar el CSV

"""

# El encoding latin-1 es necesario porque el archivo tiene caracteres especiales
# como tildes o la ñ guardados en formato antiguo (no UTF-8)
df = pd.read_csv("sales_data_sample.csv", encoding="latin-1")

print(f"✅ Dataset cargado")
print(f"   Filas    : {df.shape[0]}")
print(f"   Columnas : {df.shape[1]}")

"""#Celda 3 — Ver las primeras filas

"""

# .head() muestra las primeras 5 filas
# Sirve para ver cómo se ve la data "en crudo"
df.head()

"""#Celda 4 — Tipos de datos y nulos

"""

print("=== TIPOS DE DATOS ===")
print(df.dtypes)
print()
print("=== VALORES NULOS POR COLUMNA ===")
nulos = df.isnull().sum()
print(nulos[nulos > 0])  # Solo muestra las que tienen nulos

"""#Celda 5 — El diagnóstico del problema (la parte clave)

"""

print("=== ¿CUÁNTOS REGISTROS ÚNICOS HAY REALMENTE? ===")
print(f"Total de filas     : {len(df)}")
print(f"Órdenes únicas     : {df['ORDERNUMBER'].nunique()}")
print(f"Clientes únicos    : {df['CUSTOMERNAME'].nunique()}")
print(f"Productos únicos   : {df['PRODUCTCODE'].nunique()}")
print(f"Líneas de orden    : {len(df)}")  # cada fila ES una línea de orden
print()
print("=== CONCLUSIÓN ===")
print(f"El dataset repite datos de {df['CUSTOMERNAME'].nunique()} clientes")
print(f"en {len(df)} filas. Eso es desnormalización.")

"""#Celda 6 — Visualizar la repetición (la prueba)"""

# Tomamos un cliente cualquiera y vemos cuántas veces se repite su info
cliente = "Land of Toys Inc."
columnas_cliente = ["ORDERNUMBER", "CUSTOMERNAME", "PHONE", "ADDRESSLINE1", "CITY", "COUNTRY"]

print(f"=== Apariciones de '{cliente}' ===")
print(df[df["CUSTOMERNAME"] == cliente][columnas_cliente].to_string())

"""#Celda 7 — Resumen final del diagnóstico"""

print("=== 📋 DIAGNÓSTICO COMPLETO ===")
print()
print("Tablas que deberíamos tener (forma normalizada):")
print(f"  dim_clientes    →  {df['CUSTOMERNAME'].nunique()} filas")
print(f"  dim_productos   →  {df['PRODUCTCODE'].nunique()} filas")
print(f"  fact_ordenes    →  {df['ORDERNUMBER'].nunique()} filas")
print(f"  fact_items      →  {len(df)} filas  ← esta conserva las 2823 filas")
print()
print("Columnas por tabla:")
print("  dim_clientes  : CUSTOMERNAME, PHONE, ADDRESS, CITY, STATE,")
print("                  POSTALCODE, COUNTRY, TERRITORY, CONTACTFIRST, CONTACTLAST")
print("  dim_productos : PRODUCTCODE, PRODUCTLINE, MSRP")
print("  fact_ordenes  : ORDERNUMBER, ORDERDATE, STATUS, QTR_ID,")
print("                  MONTH_ID, YEAR_ID, DEALSIZE, CUSTOMERNAME")
print("  fact_items    : ORDERNUMBER, ORDERLINENUMBER, PRODUCTCODE,")
print("                  QUANTITYORDERED, PRICEEACH, SALES")

"""# 🔧 Paso B — Normalización del dataset
Vamos a dividir las 25 columnas en 4 tablas limpias.

Celda 8 — dim_clientes
"""

# ¿Qué hace esta celda?
# Extrae toda la información del cliente en una sola tabla.
# .drop_duplicates() elimina las filas repetidas — si el mismo cliente
# aparece 30 veces en el CSV, acá va a quedar UNA sola fila.

dim_clientes = df[[
    "CUSTOMERNAME",
    "PHONE",
    "ADDRESSLINE1",
    "ADDRESSLINE2",
    "CITY",
    "STATE",
    "POSTALCODE",
    "COUNTRY",
    "TERRITORY",
    "CONTACTLASTNAME",
    "CONTACTFIRSTNAME"
]].drop_duplicates()

# Tratamiento de NaN para columnas de texto (como hablamos)
dim_clientes["ADDRESSLINE2"] = dim_clientes["ADDRESSLINE2"].fillna("")
dim_clientes["STATE"]        = dim_clientes["STATE"].fillna("N/A")
dim_clientes["POSTALCODE"]   = dim_clientes["POSTALCODE"].fillna("N/A")
dim_clientes["TERRITORY"]    = dim_clientes["TERRITORY"].fillna("Sin asignar")

# Creamos un ID numérico único para cada cliente
# reset_index() reinicia el índice después del drop_duplicates
dim_clientes = dim_clientes.reset_index(drop=True)
dim_clientes.insert(0, "CUSTOMER_ID", dim_clientes.index + 1)

print(f"✅ dim_clientes: {dim_clientes.shape[0]} filas, {dim_clientes.shape[1]} columnas")
dim_clientes.head()

"""Celda 9 — dim_productos

"""

# Misma lógica: extraemos solo las columnas del producto
# y eliminamos duplicados. Cada producto tiene su propio código (PRODUCTCODE)
# que ya funciona como ID natural — no necesitamos crear uno nuevo.

dim_productos = df[[
    "PRODUCTCODE",
    "PRODUCTLINE",
    "MSRP"           # precio de lista sugerido por el fabricante
]].drop_duplicates()

dim_productos = dim_productos.reset_index(drop=True)

print(f"✅ dim_productos: {dim_productos.shape[0]} filas, {dim_productos.shape[1]} columnas")
dim_productos.head()

"""Celda 10 — Paso previo para fact_ordenes (unir el CUSTOMER_ID)

"""

# Antes de crear fact_ordenes necesitamos el CUSTOMER_ID que generamos
# en dim_clientes, porque fact_ordenes va a guardar la FK (foreign key)
# en vez de repetir todo el nombre y dirección del cliente.

# Hacemos un merge: unimos el df original con dim_clientes
# buscando coincidencia por CUSTOMERNAME, y traemos solo el CUSTOMER_ID

df_con_id = df.merge(
    dim_clientes[["CUSTOMER_ID", "CUSTOMERNAME"]],
    on="CUSTOMERNAME",
    how="left"
)

print(f"✅ Merge hecho. Filas: {df_con_id.shape[0]}")
print(f"   CUSTOMER_ID asignados: {df_con_id['CUSTOMER_ID'].notna().sum()}")

"""Celda 11 — fact_ordenes

"""

fact_ordenes = df_con_id[[
    "ORDERNUMBER",
    "ORDERDATE",
    "STATUS",
    "QTR_ID",
    "MONTH_ID",
    "YEAR_ID",
    "DEALSIZE",
    "CUSTOMER_ID"
]].drop_duplicates(subset=["ORDERNUMBER"])  # ← forzamos unicidad por ORDERNUMBER

fact_ordenes["ORDERDATE"] = pd.to_datetime(fact_ordenes["ORDERDATE"])
fact_ordenes = fact_ordenes.reset_index(drop=True)

print(f"✅ fact_ordenes: {fact_ordenes.shape[0]} filas")

"""Celda 12 — fact_items

"""

# Esta es la tabla de hechos principal — conserva las 2823 filas originales.
# Cada fila es una línea de orden: qué producto, cuántas unidades, a qué precio.
# No repetimos datos del cliente ni del producto, solo sus IDs (FK).

fact_items = df[[
    "ORDERNUMBER",        # FK → fact_ordenes
    "ORDERLINENUMBER",    # número de línea dentro de la orden
    "PRODUCTCODE",        # FK → dim_productos
    "QUANTITYORDERED",    # cuántas unidades
    "PRICEEACH",          # precio unitario real (puede diferir del MSRP)
    "SALES"               # total de la línea = QUANTITYORDERED * PRICEEACH
]]

fact_items = fact_items.reset_index(drop=True)

print(f"✅ fact_items: {fact_items.shape[0]} filas, {fact_items.shape[1]} columnas")
fact_items.head()

"""Celda 13 — Verificación final"""

print("=" * 45)
print("  RESUMEN DE NORMALIZACIÓN")
print("=" * 45)
print(f"  CSV original  → {df.shape[0]:>5} filas  {df.shape[1]:>3} columnas")
print("-" * 45)
print(f"  dim_clientes  → {dim_clientes.shape[0]:>5} filas  {dim_clientes.shape[1]:>3} columnas")
print(f"  dim_productos → {dim_productos.shape[0]:>5} filas  {dim_productos.shape[1]:>3} columnas")
print(f"  fact_ordenes  → {fact_ordenes.shape[0]:>5} filas  {fact_ordenes.shape[1]:>3} columnas")
print(f"  fact_items    → {fact_items.shape[0]:>5} filas  {fact_items.shape[1]:>3} columnas")
print("=" * 45)

"""Celda 14 — Exportar los 4 CSVs limpios"""

# Guardamos cada tabla como CSV separado.
# index=False evita que pandas agregue una columna extra con el número de fila.

dim_clientes.to_csv("dim_clientes.csv",   index=False)
dim_productos.to_csv("dim_productos.csv", index=False)
fact_ordenes.to_csv("fact_ordenes.csv",   index=False)
fact_items.to_csv("fact_items.csv",       index=False)

print("✅ 4 archivos exportados:")
print("   dim_clientes.csv")
print("   dim_productos.csv")
print("   fact_ordenes.csv")
print("   fact_items.csv")
print()
print("📥 Descargalos desde el panel de archivos (izquierda)")